#!/bin/sh

LEXER_FILE=WACCLexer.g4
PARSER_FILE=WACCParser.g4

BASEDIR=$(dirname $0)

TARGET_DIR=../src/main/kotlin/antlr

rm -rf $TARGET_DIR

echo Compiling the lexer..
java -jar $BASEDIR/../lib/antlr-4.9.3-complete.jar $BASEDIR/$LEXER_FILE -o $TARGET_DIR -package antlr -no-listener -visitor -Werror

if [ $? -ne 0 ]
then 
	exit 1
fi

echo Compiling the parser..
java -jar $BASEDIR/../lib/antlr-4.9.3-complete.jar $BASEDIR/$PARSER_FILE -o $TARGET_DIR -package antlr -no-listener -visitor -Werror
