package wacc

enum class RuntimeErrors {
    OVERFLOW_ERROR,
    CHECK_DIVIDE_BY_ZERO,
    CHECK_ARRAY_BOUNDS,
    FREE_PAIR_NULL_REFERENCE_ERROR,
    FREE_ARRAY_NULL_REFERENCE_ERROR,
    NULL_REFERENCE_PAIR
}